install pytorch as shown on the official site: https://pytorch.org

In [5]:
import torch

In [6]:
torch.zeros([3, 4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
torch.ones([3, 4, 2])

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

In [8]:
torch.Tensor([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [9]:
x = torch.Tensor([[1,  2,  3,  4],
                  [5,  6,  7,  8],
                  [9, 10, 11, 12]])

In [10]:
x.size()

torch.Size([3, 4])

In [11]:
x.shape

torch.Size([3, 4])

In [12]:
x[0]

tensor([1., 2., 3., 4.])

In [13]:
x[1]

tensor([5., 6., 7., 8.])

In [14]:
x[0, 0]

tensor(1.)

In [15]:
x[:, 0]

tensor([1., 5., 9.])

In [16]:
x + 10

tensor([[11., 12., 13., 14.],
        [15., 16., 17., 18.],
        [19., 20., 21., 22.]])

In [17]:
x ** 2

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.]])

In [18]:
y = torch.Tensor([[12, 11, 10, 9],
                  [8, 7, 6, 5],
                  [4, 3, 2, 1]])

In [19]:
x + y

tensor([[13., 13., 13., 13.],
        [13., 13., 13., 13.],
        [13., 13., 13., 13.]])

In [20]:
x * y

tensor([[12., 22., 30., 36.],
        [40., 42., 42., 40.],
        [36., 30., 22., 12.]])

In [21]:
x / y

tensor([[ 0.0833,  0.1818,  0.3000,  0.4444],
        [ 0.6250,  0.8571,  1.1667,  1.6000],
        [ 2.2500,  3.3333,  5.5000, 12.0000]])

In [22]:
x % y

tensor([[1., 2., 3., 4.],
        [5., 6., 1., 3.],
        [1., 1., 1., 0.]])

In [23]:
torch.exp(x)

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03],
        [8.1031e+03, 2.2026e+04, 5.9874e+04, 1.6275e+05]])

In [24]:
torch.log(x)

tensor([[0.0000, 0.6931, 1.0986, 1.3863],
        [1.6094, 1.7918, 1.9459, 2.0794],
        [2.1972, 2.3026, 2.3979, 2.4849]])

In [25]:
torch.sin(x)

tensor([[ 0.8415,  0.9093,  0.1411, -0.7568],
        [-0.9589, -0.2794,  0.6570,  0.9894],
        [ 0.4121, -0.5440, -1.0000, -0.5366]])

In [26]:
x > 3

tensor([[0, 0, 0, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.uint8)

In [27]:
mask = x > 3

In [28]:
x[mask]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [29]:
x[x > 3]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [30]:
y = x
y[0, 0] = 999
print(x)
print(y)

tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])


In [31]:
x = torch.Tensor([[1,  2,  3,  4],
                  [5,  6,  7,  8],
                  [9, 10, 11, 12]])

In [32]:
y = x.clone()
y[0, 0] = 999
print(x)
print(y)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])


In [33]:
x.dtype

torch.float32

In [34]:
x = x.double()
print(x)
x = x.int()
print(x)
x = x.float()
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], dtype=torch.float64)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [35]:
import numpy as np
x = np.array([[1, 2, 3, 4],
              [4, 3, 2, 1]])
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [36]:
x = torch.from_numpy(x)
x

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]])

In [37]:
x = x.numpy()
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [38]:
x = torch.rand([2000,3000])
# x

In [40]:
torch.cuda.is_available()

True

In [0]:
torch.device('cuda:0')

device(type='cuda', index=0)

In [0]:
torch.device('cpu')

device(type='cpu')

In [0]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda', index=0)

In [0]:
x_cuda = x.to(device)
# x_cuda

In [0]:
%time y = (x - x + x * 10.0) ** 2

CPU times: user 24.6 ms, sys: 33.9 ms, total: 58.5 ms
Wall time: 61.7 ms


In [0]:
%time y_cuda = (x_cuda - x_cuda + x_cuda * 10.0) ** 2

CPU times: user 1.55 ms, sys: 1.86 ms, total: 3.41 ms
Wall time: 24.9 ms
